apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o4ec9d4dg-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:5eb73ae862d50d7ae0fbb40f592fbf0897f8570c@sha256:105c227f3a2f35358a79557745135028edd8e33243dc924db1e2864fa56c6175
          name: container-image
